import { Hono } from "hono";
import { createDb } from "../db/client";
import { normalizeCurrency } from "../lib/currency";
import { errorResponse } from "../lib/http";
import { parseBody } from "../lib/validation";
import { parseMinorAmount } from "../lib/money";
import type { AuthVariables } from "../middleware/auth";
import { requireActiveSpaceMember, type SpaceAccessVariables } from "../middleware/space-access";
import * as service from "../services/money-accounts";
import type { Bindings } from "../types/env";

type Env={Bindings:Bindings;Variables:AuthVariables & SpaceAccessVariables};
const kinds=["cash","bank","card"] as const;
export const moneyAccountsRoute=new Hono<Env>();
moneyAccountsRoute.use("*",requireActiveSpaceMember);
moneyAccountsRoute.get("/",async(c)=>{try{return c.json({data:{moneyAccounts:await service.listMoneyAccounts(createDb(c.env.DATABASE_URL),c.req.param("spaceId")!)}})}catch{return errorResponse(c, "INTERNAL_ERROR","Internal error.")}});
moneyAccountsRoute.post("/",async(c)=>{const input=await parseCreateMoneyAccountInput(c.req.raw);if(!input)return errorResponse(c, "INVALID_REQUEST","Invalid request.");try{const account=await service.createMoneyAccountWithBalances(createDb(c.env.DATABASE_URL),{...input,spaceId:c.req.param("spaceId")!,userId:c.get("currentUserId")});return c.json({data:{account}},201)}catch{return errorResponse(c, "INTERNAL_ERROR","Internal error.")}});
moneyAccountsRoute.patch("/:accountId",async(c)=>{const input=await parsePatch(c.req.raw);if(!input)return errorResponse(c, "INVALID_REQUEST","Invalid request.");try{const db=createDb(c.env.DATABASE_URL);const spaceId=c.req.param("spaceId")!;const account=await service.findMoneyAccountInSpace(db,spaceId,c.req.param("accountId")!);if(!account)return errorResponse(c, "MONEY_ACCOUNT_NOT_FOUND","Money account not found.");if(input.isArchived===true&&await service.moneyAccountHasFutureRecurringSeries(db,spaceId,account.id))return errorResponse(c, "MONEY_ACCOUNT_IN_USE","Money account is in use.");if(input.primaryCurrency&&!await service.hasBalanceCurrency(db,account.id,input.primaryCurrency))return errorResponse(c, "INVALID_REQUEST","Invalid request.");const updated=await service.updateMoneyAccount(db,{...input,spaceId,accountId:account.id});if(!updated)return errorResponse(c, "MONEY_ACCOUNT_NOT_FOUND","Money account not found.");return c.json({data:{account:await service.findMoneyAccountWithBalances(db,spaceId,account.id)??updated}})}catch{return errorResponse(c, "INTERNAL_ERROR","Internal error.")}});
moneyAccountsRoute.put("/:accountId/balances/:currency",async(c)=>{const input=await parseBalance(c.req.raw);const currency=normalizeCurrency(c.req.param("currency"));if(!input||!currency)return errorResponse(c, "INVALID_REQUEST","Invalid request.");try{const db=createDb(c.env.DATABASE_URL);const account=await service.findMoneyAccountInSpace(db,c.req.param("spaceId")!,c.req.param("accountId")!);if(!account)return errorResponse(c, "MONEY_ACCOUNT_NOT_FOUND","Money account not found.");await service.upsertBalance(db,{accountId:account.id,currency,...input});const refreshed=await service.findMoneyAccountWithBalances(db,c.req.param("spaceId")!,account.id);const balance=refreshed?.balances.find(b=>b.currency===currency);return c.json({data:{balance}})}catch{return errorResponse(c, "INTERNAL_ERROR","Internal error.")}});
moneyAccountsRoute.delete("/:accountId/balances/:currency",async(c)=>{const currency=normalizeCurrency(c.req.param("currency"));if(!currency)return errorResponse(c, "INVALID_REQUEST","Invalid request.");try{const db=createDb(c.env.DATABASE_URL);const account=await service.findMoneyAccountInSpace(db,c.req.param("spaceId")!,c.req.param("accountId")!);if(!account)return errorResponse(c, "MONEY_ACCOUNT_NOT_FOUND","Money account not found.");if(account.primaryCurrency===currency||await service.balanceHasTransactions(db,account.id,currency)||await service.balanceHasFutureRecurringSeries(db,account.id,currency))return errorResponse(c, "BALANCE_IN_USE","Balance is in use.");if(!await service.deleteBalance(db,account.id,currency))return errorResponse(c, "BALANCE_IN_USE","Balance is in use.");return c.body(null,204)}catch{return errorResponse(c, "INTERNAL_ERROR","Internal error.")}});

function text(v:unknown,max=80){if(typeof v!=="string")return null;const s=v.trim();return s.length>0&&s.length<=max?s:null}
/**
 * Campo opcional que admite texto o `null`. Ausente y `null` significan lo
 * mismo: sin valor. `undefined` queda reservado para "tipo inválido", que es
 * lo único que debe rechazar la petición.
 *
 * Antes ausente y tipo inválido compartían sentinel, así que omitir `icon` —
 * documentado como opcional — devolvía 400.
 */
function optional(v:unknown){return v===undefined||v===null?null:typeof v==="string"?v:undefined}
export async function parseCreateMoneyAccountInput(r:Request){const b=await parseBody(r,["name","kind","icon","colorToken","primaryCurrency","balances"]);if(!b)return null;const name=text(b.name),kind=b.kind,primary=normalizeCurrency(b.primaryCurrency),balances=Array.isArray(b.balances)?b.balances:null;if(!name||!kinds.includes(kind as typeof kinds[number])||!primary||!balances?.length)return null;const parsed=[] as Array<{currency:string;openingBalanceMinor:bigint;displayOrder:number}>;for(const x of balances){if(!x||typeof x!=="object")return null;const y=x as Record<string,unknown>,currency=normalizeCurrency(y.currency),amount=parseMinorAmount(y.openingBalanceMinor);if(!currency||amount===null||!Number.isInteger(y.displayOrder)||Number(y.displayOrder)<0)return null;parsed.push({currency,openingBalanceMinor:amount,displayOrder:Number(y.displayOrder)})}if(new Set(parsed.map(x=>x.currency)).size!==parsed.length||parsed.filter(x=>x.currency===primary).length!==1)return null;const icon=optional(b.icon),colorToken=optional(b.colorToken);return icon===undefined||colorToken===undefined?null:{name,kind:kind as typeof kinds[number],icon:icon??null,colorToken:colorToken??null,primaryCurrency:primary,balances:parsed}}
async function parsePatch(r:Request){const b=await parseBody(r,["name","kind","icon","colorToken","primaryCurrency","isArchived"]);if(!b)return null;const out:Record<string,unknown>={};if("name"in b){const x=text(b.name);if(!x)return null;out.name=x}if("kind"in b){if(!kinds.includes(b.kind as typeof kinds[number]))return null;out.kind=b.kind}if("icon"in b){const x=optional(b.icon);if(x===undefined)return null;out.icon=x}if("colorToken"in b){const x=optional(b.colorToken);if(x===undefined)return null;out.colorToken=x}if("primaryCurrency"in b){const x=normalizeCurrency(b.primaryCurrency);if(!x)return null;out.primaryCurrency=x}if("isArchived"in b){if(typeof b.isArchived!=="boolean")return null;out.isArchived=b.isArchived}return Object.keys(out).length?out as Parameters<typeof service.updateMoneyAccount>[1]:null}
async function parseBalance(r:Request){const b=await parseBody(r,["openingBalanceMinor","displayOrder"]);if(!b)return null;const amount=parseMinorAmount(b.openingBalanceMinor);return amount===null||!Number.isInteger(b.displayOrder)||Number(b.displayOrder)<0?null:{openingBalanceMinor:amount,displayOrder:Number(b.displayOrder)}}
