import { Hono, type MiddlewareHandler } from "hono";
import { createDb } from "../db/client";
import { normalizeCurrency } from "../lib/currency";
import { parseIsoDate } from "../lib/date";
import { occurrenceDate } from "../lib/recurrence";
import { runRecurrences } from "../services/recurrence-engine";
import { errorResponse, type ErrorCode } from "../lib/http";
import { parseBody } from "../lib/validation";
import { parseMinorAmount } from "../lib/money";
import type { AuthVariables } from "../middleware/auth";
import { requireActiveSpaceMember, type SpaceAccessVariables } from "../middleware/space-access";
import * as financial from "../services/transactions";
import * as service from "../services/recurring-transactions";
import type { Bindings } from "../types/env";
type Env={Bindings:Bindings;Variables:AuthVariables&SpaceAccessVariables};
type Deps={createDb:typeof createDb;listSeries:typeof service.listSeries;findSeries:typeof service.findSeries;createSeries:typeof service.createSeries;updateSeries:typeof service.updateSeries;pendingNext:typeof service.pendingNext;createOccurrence:typeof service.createOccurrence;findOccurrence:typeof service.findOccurrence;findOccurrenceOn:typeof service.findOccurrenceOn;runRecurrences:typeof runRecurrences;updateOccurrence:typeof service.updateOccurrence;findActiveCategory:typeof financial.findActiveCategory;findActiveMoneyAccount:typeof financial.findActiveMoneyAccount;accountHasCurrency:typeof financial.accountHasCurrency};
const defaults:Deps={createDb,...service,runRecurrences,findActiveCategory:financial.findActiveCategory,findActiveMoneyAccount:financial.findActiveMoneyAccount,accountHasCurrency:financial.accountHasCurrency};
const frequencies=["weekly","biweekly","monthly","custom"] as const;
export function createRecurringTransactionsRoute(deps:Deps=defaults,access:MiddlewareHandler<Env>=requireActiveSpaceMember){const route=new Hono<Env>();route.use("*",access);
route.get("/",async c=>{try{return c.json({data:{recurringTransactions:await deps.listSeries(deps.createDb(c.env.DATABASE_URL),c.req.param("spaceId")!)}})}catch{return fail(c,"INTERNAL_ERROR")}});
route.post("/",async c=>{const input=await createInput(c.req.raw);if(!input)return fail(c,"INVALID_REQUEST");try{const db=deps.createDb(c.env.DATABASE_URL),spaceId=c.req.param("spaceId")!;const invalid=await relations(deps,db,spaceId,input.categoryId,input.moneyAccountId,input.currency);if(invalid)return fail(c,invalid);const recurringTransaction=await deps.createSeries(db,{...input,spaceId,userId:c.get("currentUserId")});return c.json({data:{recurringTransaction}},201)}catch{return fail(c,"INTERNAL_ERROR")}});
route.patch("/:seriesId",async c=>{const input=await patchInput(c.req.raw);if(!input)return fail(c,"INVALID_REQUEST");try{const db=deps.createDb(c.env.DATABASE_URL),spaceId=c.req.param("spaceId")!,id=c.req.param("seriesId")!,existing=await deps.findSeries(db,spaceId,id);if(!existing)return fail(c,"RECURRING_SERIES_NOT_FOUND");if((input.frequency!==undefined||input.startsOn!==undefined)&&(existing.generatedOccurrences>0||existing.frequency==="custom"||input.frequency==="custom"))return fail(c,"INVALID_REQUEST");const currency=input.currency??existing.currency,account=input.moneyAccountId===undefined?existing.moneyAccountId:input.moneyAccountId;if(input.categoryId&&!(await deps.findActiveCategory(db,spaceId,input.categoryId)))return fail(c,"CATEGORY_NOT_FOUND");if(input.moneyAccountId&&!(await deps.findActiveMoneyAccount(db,spaceId,input.moneyAccountId)))return fail(c,"MONEY_ACCOUNT_NOT_FOUND");if((input.currency!==undefined||input.moneyAccountId!==undefined)&&account&&!await deps.accountHasCurrency(db,account,currency))return fail(c,"INVALID_REQUEST");if(input.isArchived===false){input.nextOccurrenceOn=existing.frequency==="custom"?await deps.pendingNext(db,id):occurrenceDate(existing.startsOn,input.frequency??existing.frequency,existing.generatedOccurrences);}const recurringTransaction=await deps.updateSeries(db,{...input,spaceId,id});return c.json({data:{recurringTransaction}})}catch{return fail(c,"INTERNAL_ERROR")}});
route.post("/:seriesId/occurrences",async c=>{const scheduledOn=await occurrenceInput(c.req.raw,false);if(typeof scheduledOn!=="string")return fail(c,"INVALID_REQUEST");try{const db=deps.createDb(c.env.DATABASE_URL),spaceId=c.req.param("spaceId")!,id=c.req.param("seriesId")!,s=await deps.findSeries(db,spaceId,id);if(!s)return fail(c,"RECURRING_SERIES_NOT_FOUND");if(s.frequency!=="custom"||await deps.findOccurrenceOn(db,id,scheduledOn))return fail(c,"INVALID_REQUEST");const occurrence=await deps.createOccurrence(db,id,scheduledOn);const next=await deps.pendingNext(db,id);await deps.updateSeries(db,{spaceId,id,nextOccurrenceOn:next});return c.json({data:{occurrence}},201)}catch{return fail(c,"INTERNAL_ERROR")}});
route.patch("/:seriesId/occurrences/:occurrenceId",async c=>{const input=await occurrenceInput(c.req.raw,true);if(!input||typeof input==="string")return fail(c,"INVALID_REQUEST");try{const db=deps.createDb(c.env.DATABASE_URL),spaceId=c.req.param("spaceId")!,id=c.req.param("seriesId")!,s=await deps.findSeries(db,spaceId,id);if(!s)return fail(c,"RECURRING_SERIES_NOT_FOUND");if(s.frequency!=="custom")return fail(c,"INVALID_REQUEST");const existing=await deps.findOccurrence(db,id,c.req.param("occurrenceId")!);if(!existing)return fail(c,"RECURRING_OCCURRENCE_NOT_FOUND");if(existing.status!=="pending")return fail(c,"INVALID_REQUEST");const occurrence=await deps.updateOccurrence(db,id,existing.id,input);if(!occurrence)return fail(c,"INVALID_REQUEST");await deps.updateSeries(db,{spaceId,id,nextOccurrenceOn:await deps.pendingNext(db,id)});return c.json({data:{occurrence}})}catch{return fail(c,"INTERNAL_ERROR")}});  /**
   * Genera ahora los movimientos pendientes de este espacio. El cron horario
   * sigue siendo la vía normal; esto existe para no tener que esperarlo y para
   * poder comprobar el motor de punta a punta. Va acotado al espacio del que
   * ya se comprobó la membresía, así que nadie puede disparar el de otro.
   */
  route.post("/run",async c=>{try{const summary=await deps.runRecurrences(c.env.DATABASE_URL,new Date(),[c.req.param("spaceId")!]);return c.json({data:summary});}catch(error){console.error("Manual recurrence run failed:",error);return errorResponse(c,"INTERNAL_ERROR");}});
  return route;}
export const recurringTransactionsRoute=createRecurringTransactionsRoute();
function fail(c:any,code:ErrorCode){return errorResponse(c,code);}
function title(x:unknown){return typeof x==="string"&&x.trim().length>0&&x.trim().length<=120?x.trim():null}
function fields(b:Record<string,unknown>,partial:boolean){const allowed=["type","amountMinor","currency","title","categoryId","moneyAccountId","frequency","startsOn",...(partial?["isArchived"]:["customDates"])];if(Object.keys(b).some(k=>!allowed.includes(k)))return null;const x:Record<string,unknown>={};if("type"in b){if(b.type!=="income"&&b.type!=="expense")return null;x.type=b.type}if("amountMinor"in b){const n=parseMinorAmount(b.amountMinor);if(n===null||n<=0n)return null;x.amountMinor=n}if("currency"in b){const v=normalizeCurrency(b.currency);if(!v)return null;x.currency=v}if("title"in b){const v=title(b.title);if(!v)return null;x.title=v}if("categoryId"in b){if(typeof b.categoryId!=="string"||!b.categoryId)return null;x.categoryId=b.categoryId}if("moneyAccountId"in b){if(b.moneyAccountId!==null&&(typeof b.moneyAccountId!=="string"||!b.moneyAccountId))return null;x.moneyAccountId=b.moneyAccountId}if("frequency"in b){if(!frequencies.includes(b.frequency as any))return null;x.frequency=b.frequency}if("startsOn"in b){const v=parseIsoDate(b.startsOn);if(!v)return null;x.startsOn=v}if(partial&&"isArchived"in b){if(typeof b.isArchived!=="boolean")return null;x.isArchived=b.isArchived}return x}
async function createInput(r:Request){const b=await parseBody(r,["type","amountMinor","currency","title","categoryId","moneyAccountId","frequency","startsOn","customDates"]);if(!b)return null;const x=fields(b,false);if(!x||!["type","amountMinor","currency","title","categoryId","frequency"].every(k=>k in x))return null;if(x.frequency==="custom"){if("startsOn"in x||!Array.isArray(b.customDates)||!b.customDates.length)return null;const dates=b.customDates.map(parseIsoDate);if(dates.some(x=>!x)||new Set(dates).size!==dates.length)return null;return {...x,moneyAccountId:x.moneyAccountId??null,startsOn:[...dates as string[]].sort()[0],customDates:[...dates as string[]].sort()} as any}if(!("startsOn"in x)||"customDates"in b)return null;return {...x,moneyAccountId:x.moneyAccountId??null}as any}
async function patchInput(r:Request){const b=await parseBody(r,["type","amountMinor","currency","title","categoryId","moneyAccountId","frequency","startsOn","isArchived"]);if(!b)return null;const x=fields(b,true);return x&&Object.keys(x).length?x as any:null}
async function occurrenceInput(r:Request,patch:boolean){const b=await parseBody(r,["scheduledOn","status"]);if(!b)return null;if(!patch){return Object.keys(b).length===1?parseIsoDate(b.scheduledOn):null}if(Object.keys(b).length!==1)return null;if("scheduledOn"in b){const v=parseIsoDate(b.scheduledOn);return v?{scheduledOn:v}:null}return b.status==="skipped"?{status:"skipped" as const}:null}
async function relations(d:Deps,db:ReturnType<typeof createDb>,space:string,category:string,account:string|null,currency:string){if(!await d.findActiveCategory(db,space,category))return "CATEGORY_NOT_FOUND" as const;if(account&&!await d.findActiveMoneyAccount(db,space,account))return "MONEY_ACCOUNT_NOT_FOUND" as const;if(account&&!await d.accountHasCurrency(db,account,currency))return "INVALID_REQUEST" as const;return null}
