import { Hono, type MiddlewareHandler } from "hono";
import { createDb } from "../db/client";
import { normalizeCurrency } from "../lib/currency";
import { parseIsoDate } from "../lib/date";
import { errorResponse } from "../lib/http";
import { nullableString, parseBody } from "../lib/validation";
import { parseMinorAmount } from "../lib/money";
import type { AuthVariables } from "../middleware/auth";
import { requireActiveSpaceMember, type SpaceAccessVariables } from "../middleware/space-access";
import * as service from "../services/transactions";
import type { Bindings } from "../types/env";

type Env = { Bindings: Bindings; Variables: AuthVariables & SpaceAccessVariables };
type Dependencies = { createDb: typeof createDb; listTransactions: typeof service.listTransactions; findActiveCategory: typeof service.findActiveCategory; findActiveMoneyAccount: typeof service.findActiveMoneyAccount; accountHasCurrency: typeof service.accountHasCurrency; findTransactionInSpace: typeof service.findTransactionInSpace; createTransaction: typeof service.createTransaction; updateTransaction: typeof service.updateTransaction };
const defaults: Dependencies = { createDb, ...service };
export function createTransactionsRoute(deps: Dependencies = defaults, access: MiddlewareHandler<Env> = requireActiveSpaceMember) {
  const route = new Hono<Env>(); route.use("*", access);
  route.get("/", async c => { const page = parsePage(c.req.query()); if (!page) return errorResponse(c, "INVALID_REQUEST", "Invalid request."); try { const result = await deps.listTransactions(deps.createDb(c.env.DATABASE_URL), c.req.param("spaceId")!, page.limit, page.cursor); return c.json({ data: { transactions: result.transactions, nextCursor: result.nextCursor ? encodeCursor(result.nextCursor) : null } }); } catch { return errorResponse(c, "INTERNAL_ERROR", "Internal error."); } });
  route.post("/", async c => { const input = await parseCreate(c.req.raw); if (!input) return errorResponse(c, "INVALID_REQUEST", "Invalid request."); try { const db = deps.createDb(c.env.DATABASE_URL); const validation = await validateRelations(deps, db, c.req.param("spaceId")!, input.categoryId, input.moneyAccountId, input.currency, true, true); if (validation) return validation(c); const transaction = await deps.createTransaction(db, { ...input, spaceId: c.req.param("spaceId")!, userId: c.get("currentUserId") }); return c.json({ data: { transaction } }, 201); } catch { return errorResponse(c, "INTERNAL_ERROR", "Internal error."); } });
  route.patch("/:transactionId", async c => { const input = await parsePatch(c.req.raw); if (!input) return errorResponse(c, "INVALID_REQUEST", "Invalid request."); try { const db = deps.createDb(c.env.DATABASE_URL), spaceId = c.req.param("spaceId")!, transactionId = c.req.param("transactionId")!; const existing = await deps.findTransactionInSpace(db, spaceId, transactionId); if (!existing) return errorResponse(c, "TRANSACTION_NOT_FOUND", "Transaction not found."); const finalCurrency = input.currency ?? existing.currency; const finalAccount = input.moneyAccountId === undefined ? existing.moneyAccountId : input.moneyAccountId; if (input.categoryId !== undefined) { const category = await deps.findActiveCategory(db, spaceId, input.categoryId); if (!category) return errorResponse(c, "CATEGORY_NOT_FOUND", "Category not found."); } if (input.moneyAccountId !== undefined && input.moneyAccountId !== null) { const account = await deps.findActiveMoneyAccount(db, spaceId, input.moneyAccountId); if (!account) return errorResponse(c, "MONEY_ACCOUNT_NOT_FOUND", "Money account not found."); } if ((input.currency !== undefined || input.moneyAccountId !== undefined) && finalAccount && !await deps.accountHasCurrency(db, finalAccount, finalCurrency)) return errorResponse(c, "INVALID_REQUEST", "Invalid request."); const updated = await deps.updateTransaction(db, { ...input, spaceId, transactionId }); return c.json({ data: { transaction: updated } }); } catch { return errorResponse(c, "INTERNAL_ERROR", "Internal error."); } });
  return route;
}
export const transactionsRoute = createTransactionsRoute();

function encodeCursor(cursor: service.TransactionCursor) { return btoa(JSON.stringify(cursor)); }
function decodeCursor(value: string): service.TransactionCursor | null { try { const parsed: unknown = JSON.parse(atob(value)); if (!parsed || typeof parsed !== "object") return null; const x = parsed as Record<string, unknown>; return typeof x.occurredOn === "string" && typeof x.createdAt === "string" && !Number.isNaN(Date.parse(x.createdAt)) && typeof x.id === "string" ? { occurredOn: x.occurredOn, createdAt: x.createdAt, id: x.id } : null; } catch { return null; } }
function parsePage(query: Record<string, string | undefined>) { const limit = query.limit === undefined ? 50 : /^\d+$/.test(query.limit) ? Number(query.limit) : NaN; const cursor = query.cursor === undefined ? null : decodeCursor(query.cursor); return Number.isInteger(limit) && limit >= 1 && limit <= 100 && (query.cursor === undefined || cursor) ? { limit, cursor } : null; }
function title(v: unknown) {
  if (typeof v !== "string") return null;
  const normalized = v.trim();
  return normalized.length >= 1 && normalized.length <= 120 ? normalized : null;
}
function transactionFields(b: Record<string, unknown>, partial: boolean) { const out: Record<string, unknown> = {}; if ("type" in b) { if (b.type !== "expense" && b.type !== "income") return null; out.type = b.type; } if ("amountMinor" in b) { const amount = parseMinorAmount(b.amountMinor); if (amount === null || amount <= 0n) return null; out.amountMinor = amount; } if ("currency" in b) { const currency = normalizeCurrency(b.currency); if (!currency) return null; out.currency = currency; } if ("title" in b) { const value = title(b.title); if (!value) return null; out.title = value; } if ("occurredOn" in b) { const date = parseIsoDate(b.occurredOn); if (!date) return null; out.occurredOn = date; } if ("categoryId" in b) { if (typeof b.categoryId !== "string" || !b.categoryId) return null; out.categoryId = b.categoryId; } if ("moneyAccountId" in b) { if (b.moneyAccountId !== null && (typeof b.moneyAccountId !== "string" || !b.moneyAccountId)) return null; out.moneyAccountId = b.moneyAccountId; } if ("note" in b) { const note = nullableString(b.note, 2000); if (note === undefined) return null; out.note = note; } if (partial && "isArchived" in b) { if (typeof b.isArchived !== "boolean") return null; out.isArchived = b.isArchived; } return out; }
async function parseCreate(r: Request) { const b = await parseBody(r, ["type", "amountMinor", "currency", "title", "occurredOn", "categoryId", "moneyAccountId", "note"]); if (!b) return null; const input = transactionFields(b, false); return input && ["type", "amountMinor", "currency", "title", "occurredOn", "categoryId"].every(key => key in input) ? { ...input, moneyAccountId: input.moneyAccountId ?? null } as Parameters<typeof service.createTransaction>[1] extends infer _ ? Omit<Parameters<typeof service.createTransaction>[1], "spaceId" | "userId"> : never : null; }
async function parsePatch(r: Request) { const b = await parseBody(r, ["type", "amountMinor", "currency", "title", "occurredOn", "categoryId", "moneyAccountId", "note", "isArchived"]); if (!b) return null; const input = transactionFields(b, true); return input && Object.keys(input).length ? input as Omit<Parameters<typeof service.updateTransaction>[1], "spaceId" | "transactionId"> : null; }
async function validateRelations(deps: Dependencies, db: ReturnType<typeof createDb>, spaceId: string, categoryId: string, accountId: string | null, currency: string, checkCategory: boolean, checkAccount: boolean) { if (checkCategory && !await deps.findActiveCategory(db, spaceId, categoryId)) return (c: Parameters<typeof errorResponse>[0]) => errorResponse(c, "CATEGORY_NOT_FOUND", "Category not found."); if (checkAccount && accountId && !await deps.findActiveMoneyAccount(db, spaceId, accountId)) return (c: Parameters<typeof errorResponse>[0]) => errorResponse(c, "MONEY_ACCOUNT_NOT_FOUND", "Money account not found."); if (accountId && !await deps.accountHasCurrency(db, accountId, currency)) return (c: Parameters<typeof errorResponse>[0]) => errorResponse(c, "INVALID_REQUEST", "Invalid request."); return null; }
