import { and, eq } from "drizzle-orm";
import type { Database } from "../db/client";
import { categories, categoryBudgets, guestEntityLinks, guestMigrationBatches, moneyAccountBalances, moneyAccounts, recurringTransactionSeries, spaceMembers, spaces, transactions, userProfiles } from "../db/schema";

type RecordValue = Record<string, unknown>;
export type GuestPayload = { batchId:string; installationId:string; spaces:RecordValue[]; categories:RecordValue[]; moneyAccounts:RecordValue[]; recurringSeries:RecordValue[]; transactions:RecordValue[] };
export type GuestResult = { batchId:string; spaceCount:number; categoryCount:number; seriesCount:number; transactionCount:number };

export async function migrateGuest(db: Database, userId: string, payload: GuestPayload): Promise<GuestResult> {
  validate(payload);
  const result: GuestResult = { batchId: payload.batchId, spaceCount: payload.spaces.length, categoryCount: payload.categories.length, seriesCount: payload.recurringSeries.length, transactionCount: payload.transactions.length };
  const [existing] = await db.select({ status: guestMigrationBatches.status }).from(guestMigrationBatches).where(and(eq(guestMigrationBatches.userId,userId),eq(guestMigrationBatches.installationId,payload.installationId),eq(guestMigrationBatches.batchId,payload.batchId)));
  if (existing?.status === "completed") return result;
  if (existing) throw new Error("MIGRATION_IN_PROGRESS");
  const [profile] = await db.select({ personalSpaceId:userProfiles.personalSpaceId }).from(userProfiles).where(eq(userProfiles.userId,userId));
  if (!profile?.personalSpaceId) throw new Error("BOOTSTRAP_REQUIRED");
  const ids = new Map<string,string>();
  const personal = payload.spaces.find((x)=>x.type === "personal");
  for (const x of payload.spaces) ids.set(`space:${text(x.id)}`, x === personal ? profile.personalSpaceId : crypto.randomUUID());
  for (const type of ["category","account","series","transaction"] as const) for (const x of payload[ type === "category" ? "categories" : type === "account" ? "moneyAccounts" : type === "series" ? "recurringSeries" : "transactions" ]) ids.set(`${type}:${text(x.id)}`,crypto.randomUUID());
  const batchId=crypto.randomUUID(); const now=new Date(); const links=[...ids].map(([key,remoteId])=>{const [entityType,localId]=key.split(":");return {userId,installationId:payload.installationId,entityType,localId,remoteId,createdAt:now};});
  const queries = [
    db.insert(guestMigrationBatches).values({id:batchId,userId,installationId:payload.installationId,batchId:payload.batchId,status:"processing",payloadHash:hashPayload(payload),createdAt:now}),
    ...payload.spaces.filter(x=>x!==personal).map(x=>db.insert(spaces).values({id:ref(ids,"space",x.id),name:text(x.name),type:spaceType(x.type),currency:text(x.currency),timezone:"UTC",createdBy:userId,createdAt:now,updatedAt:now})),
    ...payload.spaces.filter(x=>x!==personal).map(x=>db.insert(spaceMembers).values({spaceId:ref(ids,"space",x.id),userId,role:"owner",status:"active",joinedAt:now,createdAt:now,updatedAt:now})),
    ...payload.categories.map(x=>db.insert(categories).values({id:ref(ids,"category",x.id),spaceId:ref(ids,"space",x.spaceId),name:text(x.name),icon:stringOrNull(x.icon),colorToken:stringOrNull(x.colorToken),createdBy:userId,isDefault:Boolean(x.isDefault),templateKey:stringOrNull(x.templateKey),isArchived:Boolean(x.isArchived),archivedAt:dateOrNull(x.archivedAt),createdAt:date(x.createdAt),updatedAt:date(x.updatedAt)})),
    ...payload.categories.filter(x=>typeof x.budgetMinor === "number" && x.budgetMinor >= 0).map(x=>db.insert(categoryBudgets).values({categoryId:ref(ids,"category",x.id),currency:text(x.currency ?? "EUR"),budgetAmountMinor:BigInt(x.budgetMinor as number),createdBy:userId})),
    ...payload.moneyAccounts.flatMap(x=>[db.insert(moneyAccounts).values({id:ref(ids,"account",x.id),spaceId:ref(ids,"space",x.spaceId),name:text(x.name),kind:accountKind(x.kind),icon:stringOrNull(x.icon),colorToken:stringOrNull(x.colorToken),primaryCurrency:text(x.currency),createdBy:userId,isArchived:Boolean(x.isArchived),archivedAt:dateOrNull(x.archivedAt),createdAt:date(x.createdAt),updatedAt:date(x.updatedAt)}),...array(x.balances).map(b=>db.insert(moneyAccountBalances).values({moneyAccountId:ref(ids,"account",x.id),currency:text(b.currency),openingBalanceMinor:BigInt(number(b.openingBalanceMinor)),displayOrder:number(b.position)}))]),
    ...payload.recurringSeries.map(x=>db.insert(recurringTransactionSeries).values({id:ref(ids,"series",x.id),spaceId:ref(ids,"space",x.spaceId),categoryId:ref(ids,"category",x.categoryId),moneyAccountId:x.moneyAccountId?ref(ids,"account",x.moneyAccountId):null,createdBy:userId,type:transactionType(x.type),amountMinor:BigInt(number(x.amountMinor)),currency:text(x.currency),title:text(x.title),frequency:frequency(x.frequency),startsOn:text(x.startsOn),nextOccurrenceOn:text(x.nextOccurrenceOn),generatedOccurrences:number(x.generatedOccurrences),isArchived:Boolean(x.isArchived),archivedAt:dateOrNull(x.archivedAt),createdAt:date(x.createdAt),updatedAt:date(x.updatedAt)})),
    ...payload.transactions.map(x=>db.insert(transactions).values({id:ref(ids,"transaction",x.id),spaceId:ref(ids,"space",x.spaceId),categoryId:ref(ids,"category",x.categoryId),moneyAccountId:x.moneyAccountId?ref(ids,"account",x.moneyAccountId):null,createdBy:userId,type:transactionType(x.type),amountMinor:BigInt(number(x.amountMinor)),currency:text(x.currency),title:text(x.title),occurredOn:text(x.occurredOn),recurrenceSeriesId:x.recurrenceSeriesId?ref(ids,"series",x.recurrenceSeriesId):null,isArchived:Boolean(x.isArchived),archivedAt:dateOrNull(x.archivedAt),createdAt:date(x.createdAt),updatedAt:date(x.updatedAt)})),
    db.insert(guestEntityLinks).values(links),
    db.update(guestMigrationBatches).set({status:"completed",completedAt:new Date()}).where(eq(guestMigrationBatches.id,batchId)),
  ];
  await db.batch(queries as [any, ...any[]]); return result;
}
function validate(p:GuestPayload){if(!text(p.batchId)||!text(p.installationId)||!p.spaces.some(x=>x.type==="personal"))throw new Error("INVALID_PAYLOAD"); const spaces=new Set(p.spaces.map(x=>text(x.id)));const cats=new Set(p.categories.map(x=>text(x.id)));const accounts=new Set(p.moneyAccounts.map(x=>text(x.id)));const series=new Set(p.recurringSeries.map(x=>text(x.id)));for(const x of [...p.categories,...p.moneyAccounts,...p.recurringSeries,...p.transactions])if(!spaces.has(text(x.spaceId)))throw new Error("INVALID_GRAPH");for(const x of [...p.recurringSeries,...p.transactions])if(!cats.has(text(x.categoryId)))throw new Error("INVALID_GRAPH");for(const x of [...p.recurringSeries,...p.transactions])if(x.moneyAccountId&&!accounts.has(text(x.moneyAccountId)))throw new Error("INVALID_GRAPH");for(const x of p.transactions)if(x.recurrenceSeriesId&&!series.has(text(x.recurrenceSeriesId)))throw new Error("INVALID_GRAPH");}
function ref(ids:Map<string,string>,type:string,id:unknown){const value=ids.get(`${type}:${text(id)}`);if(!value)throw new Error("INVALID_GRAPH");return value} function text(v:unknown){return typeof v==="string"&&v.trim()?v.trim():""} function number(v:unknown){if(typeof v!=="number"||!Number.isSafeInteger(v))throw new Error("INVALID_PAYLOAD");return v} function array(v:unknown){return Array.isArray(v)?v as RecordValue[]:[]} function stringOrNull(v:unknown){return typeof v==="string"?v:null} function date(v:unknown){if(typeof v!=="string"||Number.isNaN(Date.parse(v)))throw new Error("INVALID_PAYLOAD");return new Date(v)} function dateOrNull(v:unknown){return v===null?null:date(v)} function spaceType(v:unknown){if(v==="personal"||v==="couple"||v==="other")return v;throw new Error("INVALID_PAYLOAD")} function accountKind(v:unknown){if(v==="cash"||v==="bank"||v==="card")return v;throw new Error("INVALID_PAYLOAD")} function transactionType(v:unknown){if(v==="income"||v==="expense")return v;throw new Error("INVALID_PAYLOAD")} function frequency(v:unknown){if(v==="weekly"||v==="biweekly"||v==="monthly")return v;throw new Error("INVALID_PAYLOAD")} function hashPayload(p:GuestPayload){return `${p.batchId}:${p.installationId}:${p.spaces.length}:${p.categories.length}:${p.transactions.length}`}
