import { and, asc, eq, isNull } from "drizzle-orm";
import type { Database } from "../db/client";
import { recurringTransactionOccurrences as occurrences, recurringTransactionSeries as series } from "../db/schema";
import { serializeMinorAmount } from "../lib/money";

export type Frequency = "weekly" | "biweekly" | "monthly" | "custom";
export type SeriesResponse = { id:string; type:"expense"|"income"; amountMinor:string; currency:string; title:string; categoryId:string; moneyAccountId:string|null; frequency:Frequency; startsOn:string; nextOccurrenceOn:string|null; generatedOccurrences:number; createdAt:Date; updatedAt:Date; occurrences?: OccurrenceResponse[] };
export type OccurrenceResponse = { id:string; scheduledOn:string; status:"pending"|"generated"|"skipped"; generatedTransactionId:string|null };
const fields = { id:series.id,type:series.type,amountMinor:series.amountMinor,currency:series.currency,title:series.title,categoryId:series.categoryId,moneyAccountId:series.moneyAccountId,frequency:series.frequency,startsOn:series.startsOn,nextOccurrenceOn:series.nextOccurrenceOn,generatedOccurrences:series.generatedOccurrences,createdAt:series.createdAt,updatedAt:series.updatedAt };
const occurrenceFields={id:occurrences.id,scheduledOn:occurrences.scheduledOn,status:occurrences.status,generatedTransactionId:occurrences.generatedTransactionId};
const serialize=(row: Omit<SeriesResponse,"amountMinor">&{amountMinor:bigint}):SeriesResponse=>({...row,amountMinor:serializeMinorAmount(row.amountMinor)});

export async function listSeries(db:Database,spaceId:string) { const rows=await db.select(fields).from(series).where(and(eq(series.spaceId,spaceId),eq(series.isArchived,false),isNull(series.archivedAt))).orderBy(asc(series.nextOccurrenceOn),asc(series.createdAt)); const result=rows.map(serialize); const customs=result.filter(x=>x.frequency==="custom"); const all=await Promise.all(customs.map(async item=>({id:item.id,items:await listOccurrences(db,item.id)}))); for(const group of all){const target=result.find(x=>x.id===group.id); if(target) target.occurrences=group.items;} return result; }
export async function listOccurrences(db:Database,seriesId:string){return db.select(occurrenceFields).from(occurrences).where(eq(occurrences.seriesId,seriesId)).orderBy(asc(occurrences.scheduledOn));}
export async function findSeries(db:Database,spaceId:string,id:string){const [row]=await db.select({...fields,isArchived:series.isArchived}).from(series).where(and(eq(series.id,id),eq(series.spaceId,spaceId)));return row?{...serialize(row),isArchived:row.isArchived}:null;}
export async function createSeries(db:Database,input:{spaceId:string;userId:string;type:"expense"|"income";amountMinor:bigint;currency:string;title:string;categoryId:string;moneyAccountId:string|null;frequency:Frequency;startsOn:string;customDates?:string[]}){const {customDates,...values}=input;const id=crypto.randomUUID(),now=new Date(),next=input.frequency==="custom"?customDates![0]!:input.startsOn; const insert=db.insert(series).values({id,...values,nextOccurrenceOn:next,createdAt:now,updatedAt:now}); if(input.frequency==="custom"){await db.batch([insert,...customDates!.map(scheduledOn=>db.insert(occurrences).values({seriesId:id,scheduledOn,status:"pending",createdAt:now,updatedAt:now}))]);}else await insert; return {id,...input,amountMinor:serializeMinorAmount(input.amountMinor),nextOccurrenceOn:next,generatedOccurrences:0,createdAt:now,updatedAt:now} as SeriesResponse;}
export async function updateSeries(db:Database,input:{spaceId:string;id:string;type?:"expense"|"income";amountMinor?:bigint;currency?:string;title?:string;categoryId?:string;moneyAccountId?:string|null;isArchived?:boolean;startsOn?:string;frequency?:Frequency;nextOccurrenceOn?:string|null}){const values:Record<string,unknown>={updatedAt:new Date()}; for(const k of ["type","amountMinor","currency","title","categoryId","moneyAccountId","startsOn","frequency","nextOccurrenceOn"] as const)if(input[k]!==undefined)values[k]=input[k];if(input.isArchived!==undefined){values.isArchived=input.isArchived;values.archivedAt=input.isArchived?new Date():null;if(input.isArchived)values.nextOccurrenceOn=null;}const [row]=await db.update(series).set(values).where(and(eq(series.id,input.id),eq(series.spaceId,input.spaceId))).returning(fields);return row?serialize(row):null;}
export async function pendingNext(db:Database,seriesId:string){const [row]=await db.select({scheduledOn:occurrences.scheduledOn}).from(occurrences).where(and(eq(occurrences.seriesId,seriesId),eq(occurrences.status,"pending"))).orderBy(asc(occurrences.scheduledOn)).limit(1);return row?.scheduledOn??null;}
export async function createOccurrence(db:Database,seriesId:string,scheduledOn:string){const [row]=await db.insert(occurrences).values({seriesId,scheduledOn,status:"pending"}).returning(occurrenceFields);return row;}
export async function findOccurrence(db:Database,seriesId:string,id:string){const [row]=await db.select(occurrenceFields).from(occurrences).where(and(eq(occurrences.id,id),eq(occurrences.seriesId,seriesId)));return row??null;}
export async function findOccurrenceOn(db:Database,seriesId:string,scheduledOn:string){const [row]=await db.select({id:occurrences.id}).from(occurrences).where(and(eq(occurrences.seriesId,seriesId),eq(occurrences.scheduledOn,scheduledOn))).limit(1);return row??null;}
export async function updateOccurrence(db:Database,seriesId:string,id:string,input:{scheduledOn?:string;status?:"skipped"}){const [row]=await db.update(occurrences).set({...input,updatedAt:new Date()}).where(and(eq(occurrences.id,id),eq(occurrences.seriesId,seriesId),eq(occurrences.status,"pending"))).returning(occurrenceFields);return row??null;}
